### ISSUE TITLE
[intelli_plug] RUN_QUEUE_THRESHOLD not used

### ISSUE THREAD

**Issue by moddingg33k** [faux123/Nexus_5#2]
hey faux,

very nice work on your intelli_plug driver!

i figured out, that there is a line:
# define RUN_QUEUE_THRESHOLD     38

but this value doesn't get used anywhere.

did you use it in the past and is it some "garbage left over"?

**Comment by faux123** [comment]
It was used in the past, but since has been deprecated. So yes, it's left over.
