### ISSUE TITLE
[intelli_plug] export more variables to userspace

### ISSUE THREAD

**Issue by moddingg33k** [faux123/Nexus_5#3]
i'm just wondering if it would make sense to export more of the #defines to userspace, making it possible for people to tweak the behavior of your driver.

interesting values to tweak could be:
# define CPU_DOWN_FACTOR
# define DEF_SAMPLING_MS
# define BUSY_SAMPLING_MS
# define BUSY_PERSISTENCE
# define DUAL_CORE_PERSISTENCE
# define TRI_CORE_PERSISTENCE
# define QUAD_CORE_PERSISTENCE

**Comment by faux123** [comment]
Some forks of my drivers have done this already.  I personally don't feel these should be touched.  Wrong settings could lead to very poor performance and could lead to crashes.  The intelli_plug framework depends on these settings being in the correct ranges, currently the code does NOT validate or verify bogus settings, so exposing to userspace where novice users have access to these values could lead to additional headaches and pain from a long term maintenance perspective.

I follow the kernel.org philosophy.  Not everything needs to be exposed to the userspace, some should be kept within the kernel for safe keeping.

**Comment by moddingg33k** [comment]
hm, true. you convinced me :+1:
