### ISSUE TITLE
jiffies conversions: Use compile time constants when possible

### ISSUE THREAD

**Issue by moddingg33k** [faux123/Nexus_5#4]
First of all, the idea itself is great!

Unfortunately i ran into following issue:

A precompiled external kernel module is depending on the old exported symbols (usecs_to_jiffies, msecs_to_jiffies, ...) which got renamed (__usecs_to_jiffies, __msecs_to_jiffies, ...) by your commit.

Actually i understood the necessity to rename the original functions for this patch.

Since it's not an option to compile those mentioned modules against the build kernel, i would appreciate any hint to work around this issue.

Do you have any ideas?

**Comment by faux123** [comment]
hm.. can you elaborate more on these external modules?  From your post, it seemed you don't have any source to them, is this correct?  Let me think about how best to approach this.

**Comment by moddingg33k** [comment]
exactly, i got no working sourcecode for those modules (cfg80211.ko + ar6000.ko, which are used for the wifi module). that's why i extracted the prebuild ones from another kernel, shipped by the phone's manufacturer.

another issue reference: https://github.com/Blechd0se/kernel-moto-g/commit/8dd6e7542328e1eef3394d04537e1119c7d03e10
