### ISSUE TITLE
glibc versions of memcopy/memmove

### ISSUE THREAD

**Issue by moddingg33k** [faux123/Nexus_5#6]
Hey faux,

I stumbled across your extracted glibc memcopy/memove commits:

https://github.com/faux123/Nexus_5/commit/0cf8d06299567606b34406e4418deb6048652da4
https://github.com/faux123/Nexus_5/commit/a9343012a63a514b313381b980b0184b52065c2f

It seems that you are actually not making use of the glibc routines, but still work with those ARM versions. Is this intended by you?

If not there are further changes required to make the kernel using the glibc routines:
#1) arch/arm/kernel/armksyms.c

Those 2 lines need to get removed or commented out (getting export by the general lib/string.c already):

```
EXPORT_SYMBOL(memcpy)
EXPORT_SYMBOL(memmove)
```
#2) arch/arm/include/asm/string.h

Those 2 lines need to get removed as well (else they won't get export on include/linux/string.h):

```
#define __HAVE_ARCH_MEMCPY
#define __HAVE_ARCH_MEMMOVE
```
#3) arch/arm/lib/Makefile

Here both ARM modules need to get excluded from being build (compiler will otherwise complain about memset/memove routines existing twice):

```
memmove.o
memcpy.o
```

Cheers

**Comment by moddingg33k** [comment]
@StefanescuCristian: You commented out too much. You need to keep:

```
extern void * memcpy(void *, const void *, __kernel_size_t);
extern void * memmove(void *, const void *, __kernel_size_t);
```

in your "arch/arm/include/asm/string.h" and only comment out the #defines ahead of them ;-)

See @https://github.com/moddingg33k/android_kernel_experimental_old/commit/2a402efef8ff6bc55672caaf5c3d424626326773

It might be discussable why the glibc version shall be more effective than the method in the ARM tree. Benchmarks didn't show noticeable differences.

**Comment by StefanescuCristian** [comment]
I tried that already, it still complains of two definition.
I will try again later.

@moddingg33k Here is what I get when finishing the build:

lib/lib.a(string.o): In function `memcpy':
string.c:(.text+0x1cd4): multiple definition of`memcpy'
arch/arm/mach-msm/built-in.o::(.text+0x7ef10): first defined here
lib/lib.a(string.o): In function `memmove':
string.c:(.text+0x21c4): multiple definition of`memmove'
arch/arm/mach-msm/built-in.o::(.text+0x7f9a0): first defined here

I'm pretty sure I'm missing something, but I can't figure it out.

**Comment by moddingg33k** [comment]
Sounds like you didn't remove "memcpy.o" and "memmove.o" from your "arch/arm/lib/Makefile"?

Try to download and apply my patch, since it should work flawlessly: #https://github.com/moddingg33k/android_kernel_experimental_old/commit/2a402efef8ff6bc55672caaf5c3d424626326773.patch

**Comment by StefanescuCristian** [comment]
I did remove them. I grepped every file in the source and I don't have memcpy.o or memmove.o in any of them.
I tried your patch, it still fails. 
That's why I don't understand why I can't build the kernel.

I'll figure it out somehow.
